const STORE='pwA-flashcards-v1';
let saved=JSON.parse(localStorage.getItem(STORE)||'{}');
let cards=[...BASE_CARDS,...(saved.custom||[])]; let state={view:'dashboard',deck:[],index:0,flipped:false};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function persist(){localStorage.setItem(STORE,JSON.stringify(saved));}
function rating(id){return saved.progress?.[id]?.status||'new'}
function setRating(id,status){saved.progress??={};saved.progress[id]={status,at:Date.now()};persist();renderAll();}
function topics(){return [...new Set(cards.map(c=>c.topic))]}
function filtered(){let q=$('#searchInput').value.toLowerCase(),t=$('#topicFilter').value,st=$('#statusFilter').value;return cards.filter(c=>(t==='all'||c.topic===t)&&(st==='all'||rating(c.id)===st)&&(!q||`${c.q} ${c.a} ${c.s}`.toLowerCase().includes(q)))}
function initFilters(){let options=topics().map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');$('#topicFilter').innerHTML='<option value="all">Alle Themen</option>'+options;$('#formTopic').innerHTML=options;}
function progress(topic){let set=topic?cards.filter(c=>c.topic===topic):cards;let n=set.filter(c=>rating(c.id)==='good').length;return {n,total:set.length,p: set.length?Math.round(n/set.length*100):0}}
function renderDashboard(){let list=filtered();$('#topicGrid').innerHTML=topics().map(t=>{let set=list.filter(c=>c.topic===t),p=progress(t);if(!set.length)return'';return `<article class="topic-card"><div class="topic-card-top"><span>${esc(t)}</span><b>${set.length} Karten</b></div><div class="mini-progress"><span style="width:${p.p}%"></span></div><small>${p.n} von ${p.total} sicher</small><button data-action="start-topic" data-topic="${esc(t)}">Thema lernen</button></article>`}).join('')||'<p class="empty">Keine Karten entsprechen diesem Filter.</p>';
 let all=progress();$('#overallProgress').innerHTML=`<span>${all.p}% sicher</span><div class="mini-progress"><i style="width:${all.p}%"></i></div>`;let hard=cards.filter(c=>rating(c.id)==='hard'||rating(c.id)==='again').length;$('#reviewCopy').textContent=hard?`${hard} Karte${hard===1?'':'n'} warten auf Wiederholung.`:'Bewerte Karten, um deinen Wiederholungsstapel aufzubauen.';
}
function show(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));if(view==='dashboard')renderDashboard();if(view==='editor')renderEditor();}
function start(deck){if(!deck.length){alert('Für diese Auswahl gibt es keine Karten.');return}state={view:'learn',deck:[...deck],index:0,flipped:false};show('learn');renderLearn();}
function explain(c){return CARD_EXPLANATIONS[c.id]||'Die Kurzantwort nennt den prüfungsrelevanten Kern. Nutze die Quellenangabe, um den Zusammenhang im Kursmaterial nachzuvollziehen.'}
function renderLearn(){let c=state.deck[state.index];if(!c){show('dashboard');return}$('#learnMeta').textContent=`${c.topic} · ${state.index+1} / ${state.deck.length}`;$('#learnProgress').style.width=`${(state.index+1)/state.deck.length*100}%`;$('#card').classList.toggle('flipped',state.flipped);$('#cardQuestion').innerHTML=c.q;$('#cardAnswer').innerHTML=c.a;$('#cardExplanation').textContent=explain(c);$('#cardSource').textContent='Quelle: '+c.s;$('#ratingControls').hidden=!state.flipped;}
function move(d){state.index=(state.index+d+state.deck.length)%state.deck.length;state.flipped=false;renderLearn()}
function flip(){state.flipped=!state.flipped;renderLearn()}
function renderEditor(){let order=[...cards].sort((a,b)=>a.topic.localeCompare(b.topic));$('#editorList').innerHTML=order.map(c=>`<article class="editor-row"><div><span class="pill">${esc(c.topic)}</span><h3>${c.q}</h3><p>${c.s}</p></div><button data-action="edit-card" data-id="${c.id}">Bearbeiten</button></article>`).join('');}
function openEditor(card){$('#formTitle').textContent=card?'Karte bearbeiten':'Neue Karte';$('#formId').value=card?.id||'';$('#formTopic').value=card?.topic||topics()[0];$('#formType').value=card?.type||'Definition';$('#formQuestion').value=card?.q||'';$('#formAnswer').value=(card?.a||'').replace(/<[^>]+>/g,'');$('#formSource').value=card?.s||'';$('.danger').hidden=!card;$('#editDialog').showModal();}
function saveCard(){let id=$('#formId').value;let c={id:id||'custom-'+Date.now(),topic:$('#formTopic').value,type:$('#formType').value,q:$('#formQuestion').value.trim(),a:$('#formAnswer').value.trim(),s:$('#formSource').value.trim()};if(!c.q||!c.a||!c.s)return;let base=BASE_CARDS.findIndex(x=>x.id===id),custom=(saved.custom||[]).findIndex(x=>x.id===id);if(base>=0){saved.overrides??={};saved.overrides[id]=c;cards=cards.map(x=>x.id===id?c:x)}else if(custom>=0){saved.custom[custom]=c;cards=cards.map(x=>x.id===id?c:x)}else{saved.custom??=[];saved.custom.push(c);cards.push(c)}persist();$('#editDialog').close();initFilters();renderAll();}
function deleteCard(){let id=$('#formId').value;if(!id||!confirm('Diese Karte wirklich löschen?'))return;if(BASE_CARDS.some(c=>c.id===id)){saved.hidden??=[];saved.hidden.push(id)}else saved.custom=(saved.custom||[]).filter(c=>c.id!==id);cards=cards.filter(c=>c.id!==id);persist();$('#editDialog').close();renderAll();}
function renderAll(){if(state.view==='dashboard')renderDashboard();if(state.view==='editor')renderEditor();}
// gespeicherte Änderungen über die Basis legen
cards=cards.filter(c=>!(saved.hidden||[]).includes(c.id)).map(c=>saved.overrides?.[c.id]||c);
initFilters();renderDashboard();
document.addEventListener('click',e=>{let rate=e.target.closest('[data-rate]');if(rate){setRating(state.deck[state.index].id,rate.dataset.rate);move(1);return}let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action;if(a==='start-all')start(filtered());if(a==='start-topic')start(filtered().filter(c=>c.topic===b.dataset.topic));if(a==='review-hard')start(cards.filter(c=>['hard','again'].includes(rating(c.id))));if(a==='random')start([...filtered()].sort(()=>Math.random()-.5));if(a==='back')show('dashboard');if(a==='flip')flip();if(a==='previous')move(-1);if(a==='next')move(1);if(a==='shuffle'){state.deck.sort(()=>Math.random()-.5);state.index=0;renderLearn()}if(a==='open-editor')show('editor');if(a==='new-card')openEditor();if(a==='edit-card')openEditor(cards.find(c=>c.id===b.dataset.id));if(a==='delete-card')deleteCard();});
$('#card').addEventListener('click',flip);$('#searchInput').addEventListener('input',renderDashboard);$('#topicFilter').addEventListener('change',renderDashboard);$('#statusFilter').addEventListener('change',renderDashboard);$('#cardForm').addEventListener('submit',e=>{if(e.submitter?.value==='default'){e.preventDefault();saveCard()}});
document.addEventListener('keydown',e=>{if(!$('#learn').classList.contains('active')||$('#editDialog').open)return;if(e.code==='Space'){e.preventDefault();flip()}if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(['1','2','3'].includes(e.key)&&state.flipped){setRating(state.deck[state.index].id,['again','hard','good'][+e.key-1]);move(1)}});
